apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: 1d151219-a637-42e7-9fff-6fadfb6d8cac
          target-environment: Pre-prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: fc370d65-af1a-4888-9931-c4c7eaa08daa
          target-environment: prod
