apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: 884cc7f5-088a-4434-838a-6af0d3ee70fe
          target-environment: Pre-prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: fc370d65-af1a-4888-9931-c4c7eaa08daa
          target-environment: prod
